project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    linkcolor: purple
    theme: zephyr

website:
  navbar:
    background: success
    search: true
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: "Ataques a periodistas"
        contents:
          - text: "Análisis general"
            url: pages/analisis_general.ipynb
  repo-url: https://github.com/DataCritica/elecciones-argentina-2023
  repo-actions: [edit, issue]
