---
title: Análisis de tweets durante las elecciones generales 2023 en Argentina
---

## Metodología

Para llevar acabo este análisis de datos, **Data Crítica** analizó los datos recolectados por **Chequeado**. El periodo de los tweets recolectados abarca desde `30-09-2023` hasta `20-11-2023`.

Los textos de los tweets fueron clasificados programáticamente utilizando un modelo de machine learning con la librería de Python `transformers` para generar etiquetas con tipos de discursos de odio.

El modelo utilizado para este etiquetado lleva por nombre `beto-contextualized-hate-speech` en [Hugging Face](https://huggingface.co/piuba-bigdata/beto-contextualized-hate-speech) y fue elegido ya que está entrenado con datos recolectados en el contexto de Argentina.

Este modelo tiene 9 clasificaciones distintas:

| Etiqueta | Descripción |
|:---------|:------------|
| WOMEN | En contra de mujeres |
| LGBTI | En contra LGBTI |
| RACISM | Racista |
| CLASS | Clasista |
| POLITICS | Debido a política |
| DISABLED | Ableista |
| APPEARANCE | En contra debido a su apariencia |
| CRIMINAL | En contra de criminales |
| CALLS | Llamado a la violencia |

---

Jupyter Notebooks creados por Fernanda Aguirre